name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install development dependencies and project
      run: |
        pip install -e ."[dev]"

    - name: Test with pytest
      run: |
        pytest -v

    - name: Test table io from commandline
      run: |
        geomux -i example/example.tsv.gz -o results_table.tab

    - name: Test adat io from commandline
      run: |
        geomux -i example/example.h5ad -o results_table.tab
