name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -e .
        pip install pytest

    - name: Test with pytest
      run: |
        pytest -v

    - name: Test table io from commandline
      run: |
        geomux -i tests/data/table.tab -o results_table.tab

    - name: Test adat io from commandline
      run: |
        geomux -i tests/data/anndata.h5ad -o results_table.tab
